"""rename title -> name

Revision ID: c9a08bad1e53
Revises: b1d02e808673
Create Date: 2023-05-01 20:00:24.916333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a08bad1e53'
down_revision = 'b1d02e808673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('planet', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'name')
    # ### end Alembic commands ###
